# Generated by Django 2.2 on 2021-04-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210412_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
